Initial project file and structure set up
smabhena/mooov pull request #1
Opened 2022-02-24 09:41 UTC by smabhena

Created Xcode project, set up file structure and added SwiftLint

2022-02-24 17:19 UTC, bgouws requested changes
You can add .DS_Store to your .gitignore 😄

2022-02-24 17:19 UTC, bgouws commented on Mooov/Mooov/Models/MovieModel.swift
> +import Foundation
Hmm is committing this empty file intentional?

2022-02-24 17:19 UTC, bgouws commented on Mooov/Mooov/Utilities/Constants.swift
> +import Foundation
Ahh I think you're just laying out your file structure, but in future rather only commit a file when it has some code in 😄

2022-02-24 19:51 UTC, smabhena commented on Mooov/Mooov/Utilities/Constants.swift
> +import Foundation
Noted 👍

2022-02-25 13:51 UTC, bgouws requested changes
Just a little bit of clean up and then we are good to go 👍

2022-02-25 13:51 UTC, bgouws commented on .gitignore
> +.DS_Store
I would suggest *.DS_Store as it will ignore embedded files as well 😄 Also remember to delete the DS_Store files that you have already committed.

2022-02-25 13:51 UTC, bgouws commented on Mooov/Mooov/Utilities/UIImageView+Extension.swift
> +                    if let data = try? Data(contentsOf: url) {
indentation looks a little off here select all the code and then press `control + i`

2022-02-27 14:37 UTC, bgouws approved these changes
Looks good man, remember to ping your peers to also take a look so that we can get this merged 😄

2022-02-27 17:34 UTC, smabhena reviewed
Hey @tmafaralala @kirsty14, please don't forget to review my code :)

2022-02-28 05:09 UTC, kirsty14 reviewed
Very well done. I would suggest that if there is any condition that could not be true. Wrap it inside a guard let as it is much safer than an if and I would remove all comments from every file

2022-02-28 05:09 UTC, kirsty14 commented on Mooov/Mooov/Controllers/SearchResultsViewController.swift
> +
I would suggest removing this blank space as it makes the code not that easily readable

2022-02-28 05:09 UTC, kirsty14 commented on Mooov/Mooov/Controllers/SearchResultsViewController.swift
> +            print("Count: \(count)")
I think we can remove this print statement now. Ideally we want to keep our console clean with no print statements.

2022-02-28 05:09 UTC, kirsty14 commented on Mooov/Mooov/Controllers/SearchResultsViewController.swift
> +        if let res = self.results {
Using guard might not seem much different to using if, but with guard your intention is clearer: execution should not continue if your conditions are not met. I would suggest adding guard instead of if as if just check if the condition is true.

For example guard let res = self.result else {
return
}

2022-02-28 05:09 UTC, kirsty14 commented on Mooov/Mooov/Controllers/SearchResultsViewController.swift
> +        if let movieTitle = self.results?.search?[indexPath.row].title {
I would also use guard let here as well as movieTitte may not exist so we want to stop the execution of the program completely if the condition is not met

2022-02-28 05:09 UTC, kirsty14 commented on Mooov/MooovTests/MooovTests.swift
> +        // Put setup code here. This method is called before the invocation of each test method in the class.
I would also remove the comments here as these are automatically inserted when you create the test files

2022-02-28 05:09 UTC, kirsty14 commented on Mooov/MooovTests/MooovTests.swift
> +        // Use XCTAssert and related functions to verify your tests produce the correct results.
I would also remove the comments here

2022-02-28 05:09 UTC, kirsty14 commented on Mooov/MooovUITests/MooovUITests.swift
> +        // Put setup code here. This method is called before the invocation of each test method in the class.
I would remove the comments here

2022-02-28 06:55 UTC, smabhena commented on Mooov/MooovTests/MooovTests.swift
> +        // Put setup code here. This method is called before the invocation of each test method in the class.
I'm leaving these comments in for now. When we start using these tests files, I would like to read these comments as guidelines then I will remove them

2022-02-28 06:56 UTC, kirsty14 commented on Mooov/MooovTests/MooovTests.swift
> +        // Put setup code here. This method is called before the invocation of each test method in the class.
I completely understand👍🏻

2022-02-28 07:00 UTC, bgouws approved these changes
Looks good man 😄

2022-02-28 08:33 UTC, kirsty14 approved these changes
I am happy with this.

2022-02-28 09:24 UTC, tmafaralala approved these changes
Nice!...no issues from my side

2022-02-28 09:25 UTC, merged