Feature: movie information page
smabhena/mooov pull request #11
Opened 2022-03-06 14:59 UTC by smabhena

Created movie details screen and created another function to make an API call to fetch a single movie's details

2022-03-06 18:14 UTC, bgouws requested changes
Looking pretty sharp 😄 just a couple of enhancements.

2022-03-06 18:14 UTC, bgouws commented on Mooov/Mooov/Controllers/LogInViewController.swift
> +        signUpButton.layer.borderWidth = 1.0
You can add this to an `extension` to keep your styling consistent throughout your app 😄

2022-03-06 18:14 UTC, bgouws commented on Mooov/Mooov/Controllers/MovieInfoViewController.swift
> +    var movie: MovieInfo?
Think we can make these private 😄

2022-03-06 18:14 UTC, bgouws commented on Mooov/Mooov/Controllers/MovieInfoViewController.swift
> +                if let movieTitle = data.title {
So just a small note that might make things a little bit easier to handle 😄 unless your API is a little but unpredictable you can actually remove the `optionals(?)` from your model that way you won't need to unwrap everything thing here.

If you were to get `nil` from the service then you would get a parsing error. Maybe have a look and see how your API is behaving 😄

2022-03-06 18:14 UTC, bgouws commented on Mooov/Mooov/Controllers/MovieInfoViewController.swift
> +        guard let url = url else {
This will look a little bit better on one line:

`guard let url = url else { return }`

2022-03-06 18:14 UTC, bgouws commented on Mooov/Mooov/Controllers/SearchResultsViewController.swift
> +                guard let index = tableView.indexPathForSelectedRow?.row else {
You can put the return on the same line here 😄 same with line 90.

2022-03-06 18:14 UTC, bgouws commented on Mooov/Mooov/Extensions/UIColorExtension.swift
> +  static let primaryColor: UIColor = UIColor(named: "PrimaryColor")!
Nice! 


Just a small enhancement you can make here, instead of force unwrapping the colour you can maybe return a default colour that will maybe let you know there is something wrong:

`static let primaryColor = UIColor(named: "PrimaryColor") ?? UIColor.clear`

You can also let swift infer the type 😄

2022-03-06 18:14 UTC, bgouws commented on Mooov/Mooov/Models/MovieInfoModel.swift
> +    let title, year, rated, released, runtime, genre, director, writer, actors, plot, language, country, awards, poster: String?
The optional I am referring to in the other comment 😄 just incase it was not clear.

2022-03-06 18:16 UTC, bgouws commented
Remember to fill this in as well 😄 (On the side of the PR)
<img width="350" alt="Screenshot 2022-03-06 at 20 15 35" src="https://user-images.githubusercontent.com/60609865/156936324-4531d2b7-cb01-48cd-8f7d-c919bf45adf2.png">

2022-03-07 06:40 UTC, smabhena commented on Mooov/Mooov/Controllers/MovieInfoViewController.swift
> +                if let movieTitle = data.title {
Okay noted 👍

2022-03-07 06:50 UTC, smabhena commented on Mooov/Mooov/Controllers/MovieInfoViewController.swift
> +    var movie: MovieInfo?
When I make these private I'm not able to access them in the SearchResultsViewController when overriding the prepare function for the segue and passing the variable's value to the MovieInfoViewController

line 85 - 95
`
override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let movieInfoPage = segue.destination as? MovieInfoViewController {
                guard let index = tableView.indexPathForSelectedRow?.row else { return }
                guard let movie = results?.search?[index] else { return }
                
                if let movieID = movie.imdbId {
                    movieInfoPage.movieId = movieID
                }
            
        }
}
`

2022-03-07 08:39 UTC, kirsty14 commented on Mooov/Mooov/Controllers/MovieInfoViewController.swift
> +    @IBOutlet weak var movieImage: UIImageView!
These IBOutlets can be private

2022-03-07 08:39 UTC, kirsty14 commented on Mooov/Mooov/Controllers/MovieInfoViewController.swift
> +    func loadImageIntoImageView(_ imageURL: String) {
I would suggest adding this function loadImageIntoImageView to an extension as you may use this functionality again later on

2022-03-07 12:08 UTC, kirsty14 commented on Mooov/Mooov/Controllers/MovieInfoViewController.swift
> +    func loadImageIntoImageView(_ imageURL: String) {
still waiting for this

2022-03-07 12:11 UTC, smabhena commented on Mooov/Mooov/Controllers/MovieInfoViewController.swift
> +    func loadImageIntoImageView(_ imageURL: String) {
Yeah I did move it to an extension

2022-03-07 19:53 UTC, bgouws approved these changes
Happy to approve 😄

2022-03-07 19:53 UTC, bgouws commented on Mooov/Mooov/Extensions/UIViewControllerExtension.swift
> +    func loadImageIntoImageView(_ imageURL: String, _ imageView: UIImageView!) {
Hmm so this is okay here, but something to think about it might be a little bit more useful to put something like this in a `UIImageView` `extension`

2022-03-08 05:50 UTC, kirsty14 approved these changes
Looking good, Nice work Sino!

2022-03-08 06:12 UTC, kirsty14 commented on Mooov/Mooov/Controllers/MovieInfoViewController.swift
> +    var movieTitle: String?
Just a suggestion. I would make these variables private as you not using it outside of this class

2022-03-08 06:12 UTC, kirsty14 commented on Mooov/Mooov/Controllers/MovieInfoViewController.swift
> +    var movieTitle: String?
Also do you still use movieTitle. it does not seem like it is used

2022-03-08 06:12 UTC, kirsty14 commented on Mooov/Mooov/Controllers/SearchResultsViewController.swift
>      var searchText: String = ""
I would also make this private as you not going to use this variable outside of this class

2022-03-08 06:17 UTC, kirsty14 commented on Mooov/Mooov/Controllers/SearchResultsViewController.swift
>      var searchText: String = ""
Could you possibly also add a description and screenshots of your Pull request so that it gives us reviewers more insight visually into what the changes are.

2022-03-08 06:37 UTC, simekanidvt approved these changes
Looks good to me

2022-03-08 06:57 UTC, merged