Refactored Search Movie Feature
smabhena/mooov pull request #20
Opened 2022-03-23 09:23 UTC by smabhena

The rest of the features will be refactored in coming pull requests

2022-03-23 12:48 UTC, bgouws commented on Mooov/Mooov/Search Movie/SearchResultsViewController.swift
> +    private lazy var viewModel = SearchMovieViewModel(repository: SearchMovieRepository(), delegate: self)
Just a small code style thing 😄 

But you can put each parameter on its own line.

```
private lazy var viewModel = SearchMovieViewModel(repository: SearchMovieRepository(),
                                                  delegate: self)
```

2022-03-23 12:52 UTC, bgouws commented on Mooov/Mooov/Search Movie/SearchResultsViewController.swift
>      private var results: SearchResults?
Your ViewController doesn't need to know about `SearchResults ` 😄

2022-03-23 12:55 UTC, bgouws commented on Mooov/Mooov/Search Movie/SearchResultsViewController.swift
> +        guard let movieTitle = viewModel.results?.search[indexPath.row].title else {
Why not have a `func` in your `ViewModel` that returns the movieTitle ready to use?

2022-03-23 12:56 UTC, bgouws commented on Mooov/Mooov/Search Movie/SearchResultsViewController.swift
> +                guard let movie = viewModel.results?.search[index] else { return }
You can reuse that `func` I mentioned in the previous comment.

2022-03-23 12:57 UTC, bgouws commented on Mooov/Mooov/Search Movie/SearchResultsViewController.swift
> +        displayAlert(title: "Error", message: error, buttonTitle: "Ok")
Each parameter on its own line 😄

2022-03-23 13:47 UTC, simekanidvt requested changes

2022-03-23 13:47 UTC, simekanidvt commented on Mooov/Mooov/Search Movie/Repository/SearchMovieRepository.swift
> +    private func call<T: Codable>(with request: URLRequest, completion: @escaping((Result<T, APIError>) -> Void)) {
You could make use of typealias to make this look cleaner, for this -> "(Result<T, APIError>) -> Void)"

2022-03-24 07:31 UTC, kirsty14 submitted a review, later dismissed
Looking a lot cleaner. Nice work!

2022-03-24 09:28 UTC, kirsty14 approved these changes

2022-03-24 10:27 UTC, simekanidvt approved these changes

2022-03-24 14:02 UTC, bgouws approved these changes
Just those naming enhancements but looks really good 👍

2022-03-24 14:40 UTC, smabhena commented on Mooov/Mooov/Search Movie/SearchMovieViewModel.swift
> +    func getMovieTitle(_ atIndex: Int) -> String? {
Noted, will fix it in my next PR 👍

2022-03-24 14:41 UTC, merged