Feature refactor saved movies and movie info
smabhena/mooov pull request #22
Opened 2022-03-28 08:12 UTC by smabhena

Refactored Movie Info and Saved Movie features
- Created a single repository that is shared 
- Refactored Movie Info feature
- Refactored Saved Movie feature
- Fixed delete movie bug

2022-03-28 11:02 UTC, bgouws requested changes
Some clean up 😄

2022-03-28 11:02 UTC, bgouws commented on Mooov/Mooov/Save Movie/SaveMovieViewModel.swift
> +        guard let context = Constants.viewContext else {
You can move code like this to a file called `SaveMovieRepository`

2022-03-29 13:41 UTC, bgouws requested changes
Looking good, maybe just update that one `ViewController`  to use the repo rather than access `CoreData` directly.

2022-03-29 13:41 UTC, bgouws commented on Mooov/Mooov/Movie Info/MovieInfoViewController.swift
> +    private var id: String?
Do we need to have these variables here?

2022-03-29 13:41 UTC, bgouws commented on Mooov/Mooov/Movie Info/MovieInfoViewController.swift
> +    func setMovieId(_ id: String) {
Rather pass this through as one object and then set it in your `ViewModel`. 😄

2022-03-29 13:41 UTC, bgouws commented on Mooov/Mooov/Movie Info/MovieInfoViewModel.swift
> +        guard let title = title, let image = image, let context = Constants.viewContext else { return }
Why not call the repository here? 😄

2022-03-29 13:41 UTC, bgouws commented on Mooov/Mooov/Movie Info/MovieInfoViewModel.swift
> +            guard let movies = try Constants.viewContext?.fetch(MovieItem.fetchRequest()) else { return }
Same as above here 😄

2022-03-29 13:41 UTC, bgouws commented on Mooov/Mooov/Save Movie/SaveMovieViewModel.swift
> +        repository?.fetchSavedMovies(completion: { [weak self] movies in
Very nice! 😄

2022-03-29 14:14 UTC, smabhena commented on Mooov/Mooov/Movie Info/MovieInfoViewController.swift
> +    private var id: String?
Yeah they're used to hold the data sent from the SearchResultsViewController

2022-03-29 19:56 UTC, bgouws requested changes
Some more clean up

2022-03-29 19:56 UTC, bgouws commented on Mooov/Mooov/Movie Info/MovieInfoViewModel.swift
> +    private var coreDataRepository: CoreDataRepository?
Use a `protocol` to abstract this `repository` 😄

2022-03-29 19:56 UTC, bgouws commented on Mooov/Mooov/Movie Info/MovieInfoViewModel.swift
> +         coreDataRepository: CoreDataRepository,
Here too 😄

2022-03-29 19:56 UTC, bgouws commented on Mooov/Mooov/Movie Info/MovieInfoViewModel.swift
> +        coreDataRepository?.createMovieItem(movie: movie, completion: { [weak self] result in
Nice!

2022-03-29 19:56 UTC, bgouws commented on Mooov/Mooov/Save Movie/SaveMovieViewModel.swift
> +    private var repository: CoreDataRepository?
You can also abstract the type here with a `protocol`

2022-03-29 19:56 UTC, bgouws commented on Mooov/Mooov/Save Movie/SaveMovieViewModel.swift
> +    init(delegate: SaveMovieViewDelegate, repository: CoreDataRepository) {
Here too 😄 and parameters on their own line 👍

2022-03-30 07:18 UTC, kirsty14 commented on Mooov/Mooov/Save Movie/SaveMovieViewModel.swift
> +        guard let context = Constants.viewContext else {
I agree with this 👍🏻

2022-03-30 07:19 UTC, kirsty14 commented on Mooov/Mooov/Save Movie/SaveMovieViewModel.swift
> +    private var repository: CoreDataRepository?
I agree with this 👍🏻

2022-03-30 07:19 UTC, kirsty14 commented on Mooov/Mooov/Movie Info/MovieInfoViewModel.swift
> +         coreDataRepository: CoreDataRepository,
I agree with this 👍🏻

2022-03-30 07:19 UTC, kirsty14 commented on Mooov/Mooov/Movie Info/MovieInfoViewModel.swift
> +    private var coreDataRepository: CoreDataRepository?
I agree with this 👍🏻

2022-03-30 07:20 UTC, kirsty14 commented on Mooov/Mooov/Save Movie/SaveMovieViewModel.swift
> +    init(delegate: SaveMovieViewDelegate, repository: CoreDataRepository) {
I agree with this 👍🏻

2022-03-30 09:59 UTC, kirsty14 approved these changes
Looking good! 👍🏻

2022-03-30 20:50 UTC, bgouws approved these changes

2022-03-30 20:51 UTC, merged