Feature new release section
smabhena/mooov pull request #24
Opened 2022-04-06 12:07 UTC by smabhena

Added in new releases section to home page

<img width="190" alt="Screenshot 2022-04-06 at 14 06 34" src="https://user-images.githubusercontent.com/100207221/161970877-2f8eec20-ca8e-44e1-b669-327a6d4a4882.png">

2022-04-06 15:24 UTC, erikdvt commented on Mooov/MooovTests/HomeTests/HomeTests.swift
> +
You have an extra new line here.

2022-04-06 15:24 UTC, erikdvt commented on Mooov/MooovTests/MockRepository.swift
> +    let result: SearchResults = SearchResults(search: [Movie(title: "Batman", year: "2022", imdbId: "9/10", type: "Movie", poster: "Poster")], totalResults: "1", response: "true")
Maybe you could improve the readability of this? You could store it in a mock JSON file or just split it over multiple lines.

2022-04-06 19:45 UTC, bgouws requested changes
Looks pretty good, just a few enhancements 😄

2022-04-06 19:45 UTC, bgouws commented on Mooov/Mooov/Home/Custom Cells/CollectionViewCell.swift
> +    @IBOutlet weak var movieImageView: UIImageView!
These can be `private`

2022-04-06 19:45 UTC, bgouws commented on Mooov/Mooov/Home/HomePageViewController.swift
> +    @IBOutlet weak var collectionView: UICollectionView!
This can be `private` 😄

2022-04-06 19:45 UTC, bgouws commented on Mooov/Mooov/Home/HomePageViewController.swift
> +    private lazy var viewModel = HomePageViewModel(delegate: self, repository: MovieRepository())
Just a code style tip but you can put each parameter on its own line.

2022-04-06 19:45 UTC, bgouws commented on Mooov/Mooov/Home/HomePageViewModel.swift
> +        repository?.fetchMovie("tt1877830", completion: { [weak self] result in
Are these movies hardcoded for now?

2022-04-06 19:45 UTC, bgouws commented on Mooov/MooovTests/MockRepository.swift
> +    let result: SearchResults = SearchResults(search: [Movie(title: "Batman", year: "2022", imdbId: "9/10", type: "Movie", poster: "Poster")], totalResults: "1", response: "true")
Each parameter on it's own line will be fine 😄

2022-04-06 19:45 UTC, bgouws commented on Mooov/MooovTests/HomeTests/MockDelegate.swift
> +class MockDelegate: HomePageViewModelDelegate {
You can actually put this `MockDelegate` `class` inside `class HomeTests: XCTestCase {`

2022-04-06 19:45 UTC, bgouws commented on Mooov/MooovTests/MockRepository.swift
> +class MockRepository: MovieRepositoryType {
This could also live inside of `class HomeTests: XCTestCase {` 😄

2022-04-07 06:01 UTC, smabhena commented on Mooov/Mooov/Home/HomePageViewModel.swift
> +        repository?.fetchMovie("tt1877830", completion: { [weak self] result in
Yes, the problem is my API only has two endpoints (get by id and get by search) so when it comes to a feature like this it doesn't have a new releases endpoint or an endpoint where i can get a bunch of movies from a certain date so it has to be hardcoded.

2022-04-07 08:39 UTC, kirsty14 submitted a review, later dismissed
Looking good 👍🏻

2022-04-07 20:09 UTC, bgouws requested changes

2022-04-07 20:09 UTC, bgouws commented on Mooov/Mooov/Home/HomePageViewModel.swift
> +    func fetchMovies() {
So you should be able to test this too 😄 let me know if you need help 👍

2022-04-07 20:09 UTC, bgouws commented on Mooov/MooovTests/HomeTests/HomeTests.swift
> +}
Tests are looking great! lets see if we can get that last function tested 😄

2022-04-11 05:32 UTC, bgouws requested changes

2022-04-11 05:32 UTC, bgouws commented on Mooov/MooovTests/HomeTests/HomeTests.swift
> +class MockDelegate: HomePageViewModelDelegate {
Might be better to encapsulate these mock classes in `HomeTests` that way when you write tests for another class you can reuse the same naming 😄

2022-04-11 05:36 UTC, smabhena commented on Mooov/MooovTests/HomeTests/HomeTests.swift
> +class MockDelegate: HomePageViewModelDelegate {
Okay on it

2022-04-11 06:37 UTC, kirsty14 submitted a review, later dismissed
Looking good 👍🏻

2022-04-11 19:38 UTC, bgouws approved these changes
Looks good 👍

2022-04-12 06:37 UTC, merged