Feature login page
smabhena/mooov pull request #3
Opened 2022-02-28 09:27 UTC by smabhena

Added a login screen and landing page. Login makes use of a hardcoded username and password. Upon successfully logging in, the app is directed to the landing page.

2022-02-28 09:39 UTC, kirsty14 submitted a review, later dismissed
Good work. I do not see any issues in your code.

2022-02-28 11:59 UTC, tmafaralala commented on Mooov/Mooov/Controllers/LogInViewController.swift
> +            guard let vc = vc else {
😄 I'd suggest making the let  and the guard let one thing... otherwise everything looks good👍

2022-02-28 11:59 UTC, tmafaralala submitted a review, later dismissed
Great stuff👍.

2022-02-28 15:47 UTC, kieranwoodrow commented on Mooov/Mooov/Controllers/LogInViewController.swift
> +            guard let vc = vc else {
Maybe just give the variables a set explanatory name instead of just vc. Otherwise, looking good bro

2022-02-28 15:48 UTC, kieranwoodrow approved these changes
Keep it up!

2022-02-28 20:07 UTC, bgouws requested changes
Just a couple of enhancements, but it's looking good thus far.

2022-02-28 20:07 UTC, bgouws commented on Mooov/Mooov/Controllers/LogInViewController.swift
> +            guard let vc = vc else {
I agree with @kieranwoodrow  here, instead of `vc` you can call it something like `landingPageScreen` 😄

2022-02-28 20:07 UTC, bgouws commented on Mooov/Mooov/Controllers/LogInViewController.swift
> +extension UIViewController {
Very nice! 😄 The only improvement I would suggest is to move this to it's own file because we are going to use it everywhere (not that we wouldn't be able to access it like this, but I think you get the point 😃)

2022-03-01 09:09 UTC, kirsty14 approved these changes
Good work! Keep it up

2022-03-01 20:16 UTC, bgouws approved these changes
Looks good 😄

2022-03-02 10:46 UTC, kieranwoodrow approved these changes
Looking good! Keep it up!

2022-03-02 10:46 UTC, merged