Feature navigation bar
smabhena/mooov pull request #8
Opened 2022-03-02 10:05 UTC by smabhena

Made use of a tab bar controller to set up the nav bar and navigation of the app to the main screens. Also fixed navigation between screens.

2022-03-02 20:12 UTC, bgouws requested changes
Just a little bit of clean up 😄

2022-03-02 20:12 UTC, bgouws commented on Mooov/Mooov/Controllers/LogInViewController.swift
> +
You can group these `@IBOutlets` together will make things a bit neater 😄 


```
@IBOutlet weak var usernameField: UITextField!
@IBOutlet weak var passwordField: UITextField!
```

2022-03-02 20:12 UTC, bgouws commented on Mooov/Mooov/Controllers/LogInViewController.swift
> +    override func viewDidLoad() {
Just another code style comment, normally we like to keep our life cycle functions at the top of the class 😄

2022-03-03 05:44 UTC, kirsty14 approved these changes
Looking good! Keep up the good work

2022-03-03 07:30 UTC, kirsty14 approved these changes

2022-03-03 20:14 UTC, bgouws approved these changes
Happy from my side 😄

2022-03-06 14:51 UTC, simekanidvt approved these changes

2022-03-06 14:53 UTC, merged